/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicemanagement;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author pdeshmukh
 */
public class ForgotPasswordUI extends javax.swing.JFrame {

    private int xx;
    private int xy;

    /**
     * Creates new form Home
     */
    public ForgotPasswordUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_pnl = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        user_icon_lbl = new javax.swing.JLabel();
        inv_mgmt_login_lbl = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        exit_pnl = new javax.swing.JPanel();
        exit_lbl = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        username_lbl = new javax.swing.JLabel();
        new_password_lbl = new javax.swing.JLabel();
        new_password_input = new javax.swing.JPasswordField();
        user_login_heading_lbl = new javax.swing.JLabel();
        confirm_password_lbl = new javax.swing.JLabel();
        chng_password_btn_pnl = new javax.swing.JPanel();
        change_password_btn_lbl = new javax.swing.JLabel();
        confirm_password_input = new javax.swing.JPasswordField();
        email_lbl = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        error_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setResizable(false);

        login_pnl.setBackground(new java.awt.Color(255, 255, 255));
        login_pnl.setLayout(null);

        sidebar.setBackground(new java.awt.Color(0, 102, 204));
        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sidebarMouseReleased(evt);
            }
        });

        user_icon_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invoicemanagement/User.png"))); // NOI18N

        inv_mgmt_login_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        inv_mgmt_login_lbl.setForeground(new java.awt.Color(255, 255, 255));
        inv_mgmt_login_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inv_mgmt_login_lbl.setText("Reset Password");

        back.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invoicemanagement/back.png"))); // NOI18N
        back.setToolTipText("Return to Log In Screen");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user_icon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(inv_mgmt_login_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(user_icon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inv_mgmt_login_lbl)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        login_pnl.add(sidebar);
        sidebar.setBounds(0, 0, 260, 565);

        exit_pnl.setBackground(new java.awt.Color(0, 102, 204));
        exit_pnl.setPreferredSize(new java.awt.Dimension(40, 40));

        exit_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        exit_lbl.setForeground(new java.awt.Color(255, 255, 255));
        exit_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invoicemanagement/close.png"))); // NOI18N
        exit_lbl.setToolTipText("Exit");
        exit_lbl.setAlignmentY(0.0F);
        exit_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit_lbl.setPreferredSize(new java.awt.Dimension(40, 40));
        exit_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exit_pnlLayout = new javax.swing.GroupLayout(exit_pnl);
        exit_pnl.setLayout(exit_pnlLayout);
        exit_pnlLayout.setHorizontalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exit_pnlLayout.setVerticalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        login_pnl.add(exit_pnl);
        exit_pnl.setBounds(1002, 0, 40, 40);

        username_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        username_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });
        login_pnl.add(username_input);
        username_input.setBounds(325, 120, 650, 40);

        username_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        username_lbl.setText("Username");
        login_pnl.add(username_lbl);
        username_lbl.setBounds(325, 90, 650, 30);

        new_password_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        new_password_lbl.setText("New Password");
        login_pnl.add(new_password_lbl);
        new_password_lbl.setBounds(325, 270, 650, 30);

        new_password_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        new_password_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        login_pnl.add(new_password_input);
        new_password_input.setBounds(325, 300, 650, 40);

        user_login_heading_lbl.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        user_login_heading_lbl.setForeground(new java.awt.Color(102, 102, 102));
        user_login_heading_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_login_heading_lbl.setText("Invoice Management");
        login_pnl.add(user_login_heading_lbl);
        user_login_heading_lbl.setBounds(325, 40, 650, 40);

        confirm_password_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        confirm_password_lbl.setText("Confirm Password");
        login_pnl.add(confirm_password_lbl);
        confirm_password_lbl.setBounds(325, 360, 650, 30);

        chng_password_btn_pnl.setBackground(new java.awt.Color(0, 102, 204));
        chng_password_btn_pnl.setForeground(new java.awt.Color(255, 255, 255));
        chng_password_btn_pnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        change_password_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        change_password_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        change_password_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        change_password_btn_lbl.setText("Change Password");
        change_password_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                change_password_btn_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout chng_password_btn_pnlLayout = new javax.swing.GroupLayout(chng_password_btn_pnl);
        chng_password_btn_pnl.setLayout(chng_password_btn_pnlLayout);
        chng_password_btn_pnlLayout.setHorizontalGroup(
            chng_password_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(change_password_btn_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        chng_password_btn_pnlLayout.setVerticalGroup(
            chng_password_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chng_password_btn_pnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(change_password_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        change_password_btn_lbl.getAccessibleContext().setAccessibleParent(login_pnl);

        login_pnl.add(chng_password_btn_pnl);
        chng_password_btn_pnl.setBounds(520, 460, 340, 50);

        confirm_password_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        confirm_password_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        login_pnl.add(confirm_password_input);
        confirm_password_input.setBounds(325, 390, 650, 40);

        email_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        email_lbl.setText("Email ID");
        login_pnl.add(email_lbl);
        email_lbl.setBounds(325, 180, 650, 30);

        email_input.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        email_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        email_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_inputActionPerformed(evt);
            }
        });
        login_pnl.add(email_input);
        email_input.setBounds(325, 210, 650, 40);

        error_lbl.setBackground(new java.awt.Color(240, 240, 240));
        error_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        error_lbl.setForeground(new java.awt.Color(204, 0, 0));
        error_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_pnl.add(error_lbl);
        error_lbl.setBounds(325, 520, 650, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1042, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void exit_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_lblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_lblMouseClicked

    private void change_password_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_change_password_btn_lblMouseClicked
        PreparedStatement ps;
        ResultSet rs;
        int update;
        String username = username_input.getText();
        String email = email_input.getText();
        String new_password = String.valueOf(new_password_input.getPassword());
        String confirm_password = String.valueOf(confirm_password_input.getPassword());
        
        String confirmUnameQuery = "Select * FROM `inv_users` WHERE `uname` = ? AND `uemail` = ?";
        String updatePasswordquery = "UPDATE inv_users SET upass = ? WHERE uname = ? AND uemail = ?";
        
        try {
            if(new_password.isEmpty() || confirm_password.isEmpty() || email.isEmpty() || username.isEmpty()) {
                error_lbl.setText("Please fill up all fields");
            } else {
                if(new_password.equals(confirm_password)) {
                    error_lbl.setText("");

                    ps = DbConnection.getConnection().prepareStatement(confirmUnameQuery);
                    
                    ps.setString(1, username);
                    ps.setString(2, email);

                    rs = ps.executeQuery();
                    
                    if (rs.next()) {
                        error_lbl.setText("");
                        ps = DbConnection.getConnection().prepareStatement(updatePasswordquery);
                        ps.setString(1, confirm_password);
                        ps.setString(2, username);
                        ps.setString(3, email);

                        update = ps.executeUpdate();
                        
                        if(update > 0) {
                            JOptionPane.showMessageDialog(null, "Password Updated!");
                            error_lbl.setText("");
                            this.dispose();
                            new LoginUI().setVisible(true);
                        } else {
                            error_lbl.setText("There was an error updating the password.");
                        }   
                    } else {
                        error_lbl.setText("This Email ID does not belong to this Username in our records.");
                    }
                } else {
                    error_lbl.setText("Both passwords do not match.");
                }
            }            
        } catch (SQLException ex) {
            Logger.getLogger(ForgotPasswordUI.class.getName()).log(Level.SEVERE, null, ex);
        }       

    }//GEN-LAST:event_change_password_btn_lblMouseClicked

    private void email_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_inputActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new LoginUI().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMousePressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_sidebarMousePressed

    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_sidebarMouseDragged

    private void sidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_sidebarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPasswordUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPasswordUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel change_password_btn_lbl;
    private javax.swing.JPanel chng_password_btn_pnl;
    private javax.swing.JPasswordField confirm_password_input;
    private javax.swing.JLabel confirm_password_lbl;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JLabel error_lbl;
    private javax.swing.JLabel exit_lbl;
    private javax.swing.JPanel exit_pnl;
    private javax.swing.JLabel inv_mgmt_login_lbl;
    private javax.swing.JPanel login_pnl;
    private javax.swing.JPasswordField new_password_input;
    private javax.swing.JLabel new_password_lbl;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel user_icon_lbl;
    private javax.swing.JLabel user_login_heading_lbl;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_lbl;
    // End of variables declaration//GEN-END:variables
}
