/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicemanagement;

import java.awt.GraphicsEnvironment;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author pdeshmukh
 */
public class LoginUI extends javax.swing.JFrame {

    private int xx;
    private int xy;
    private boolean maximized = true;

    /**
     * Creates new form Home
     */
    public LoginUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_pnl = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        user_icon_lbl = new javax.swing.JLabel();
        inv_mgmt_login_lbl = new javax.swing.JLabel();
        exit_pnl = new javax.swing.JPanel();
        exit_lbl = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        username_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        password_input = new javax.swing.JPasswordField();
        forgot_password_lbl = new javax.swing.JLabel();
        user_login_heading_lbl = new javax.swing.JLabel();
        error_lbl = new javax.swing.JLabel();
        login_btn_pnl = new javax.swing.JPanel();
        login_btn_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setResizable(false);

        login_pnl.setBackground(new java.awt.Color(255, 255, 255));
        login_pnl.setLayout(null);

        sidebar.setBackground(new java.awt.Color(0, 102, 204));
        sidebar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidebarMouseDragged(evt);
            }
        });
        sidebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidebarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sidebarMouseReleased(evt);
            }
        });

        user_icon_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invoicemanagement/User.png"))); // NOI18N

        inv_mgmt_login_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        inv_mgmt_login_lbl.setForeground(new java.awt.Color(255, 255, 255));
        inv_mgmt_login_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inv_mgmt_login_lbl.setText("Login");

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inv_mgmt_login_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(user_icon_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(user_icon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inv_mgmt_login_lbl)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        login_pnl.add(sidebar);
        sidebar.setBounds(0, 0, 260, 565);

        exit_pnl.setBackground(new java.awt.Color(0, 102, 204));
        exit_pnl.setPreferredSize(new java.awt.Dimension(40, 40));

        exit_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        exit_lbl.setForeground(new java.awt.Color(255, 255, 255));
        exit_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/invoicemanagement/close.png"))); // NOI18N
        exit_lbl.setToolTipText("Exit");
        exit_lbl.setAlignmentY(0.0F);
        exit_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_lbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exit_lbl.setPreferredSize(new java.awt.Dimension(40, 40));
        exit_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exit_pnlLayout = new javax.swing.GroupLayout(exit_pnl);
        exit_pnl.setLayout(exit_pnlLayout);
        exit_pnlLayout.setHorizontalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        exit_pnlLayout.setVerticalGroup(
            exit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exit_pnlLayout.createSequentialGroup()
                .addComponent(exit_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        login_pnl.add(exit_pnl);
        exit_pnl.setBounds(1002, 0, 40, 40);

        username_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        username_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        username_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_inputActionPerformed(evt);
            }
        });
        login_pnl.add(username_input);
        username_input.setBounds(325, 150, 650, 40);

        username_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        username_lbl.setText("Username");
        login_pnl.add(username_lbl);
        username_lbl.setBounds(325, 120, 650, 30);

        password_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        password_lbl.setText("Password");
        login_pnl.add(password_lbl);
        password_lbl.setBounds(325, 250, 650, 30);

        password_input.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        password_input.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        password_input.setNextFocusableComponent(login_btn_lbl);
        login_pnl.add(password_input);
        password_input.setBounds(325, 280, 650, 40);

        forgot_password_lbl.setBackground(new java.awt.Color(240, 240, 240));
        forgot_password_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        forgot_password_lbl.setForeground(new java.awt.Color(0, 102, 204));
        forgot_password_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgot_password_lbl.setText("Forgot Password?");
        forgot_password_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgot_password_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgot_password_lblMouseClicked(evt);
            }
        });
        login_pnl.add(forgot_password_lbl);
        forgot_password_lbl.setBounds(325, 440, 650, 30);

        user_login_heading_lbl.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        user_login_heading_lbl.setForeground(new java.awt.Color(102, 102, 102));
        user_login_heading_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_login_heading_lbl.setText("Invoice Management");
        login_pnl.add(user_login_heading_lbl);
        user_login_heading_lbl.setBounds(325, 40, 650, 40);

        error_lbl.setBackground(new java.awt.Color(240, 240, 240));
        error_lbl.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        error_lbl.setForeground(new java.awt.Color(204, 0, 0));
        error_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login_pnl.add(error_lbl);
        error_lbl.setBounds(325, 510, 650, 30);

        login_btn_pnl.setBackground(new java.awt.Color(0, 102, 204));
        login_btn_pnl.setForeground(new java.awt.Color(255, 255, 255));
        login_btn_pnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        login_btn_lbl.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        login_btn_lbl.setForeground(new java.awt.Color(255, 255, 255));
        login_btn_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_btn_lbl.setText("Login");
        login_btn_lbl.setAlignmentY(0.0F);
        login_btn_lbl.setFocusCycleRoot(true);
        login_btn_lbl.setName("login_btn"); // NOI18N
        login_btn_lbl.setNextFocusableComponent(forgot_password_lbl);
        login_btn_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_btn_lblMouseClicked(evt);
            }
        });
        login_btn_lbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                login_btn_lblKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout login_btn_pnlLayout = new javax.swing.GroupLayout(login_btn_pnl);
        login_btn_pnl.setLayout(login_btn_pnlLayout);
        login_btn_pnlLayout.setHorizontalGroup(
            login_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_btn_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        login_btn_pnlLayout.setVerticalGroup(
            login_btn_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_btn_pnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login_btn_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        login_pnl.add(login_btn_pnl);
        login_btn_pnl.setBounds(480, 370, 320, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(login_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1042, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_inputActionPerformed

    private void login_btn_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_btn_lblMouseClicked
        this.attempt_login();

    }//GEN-LAST:event_login_btn_lblMouseClicked

    private void forgot_password_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgot_password_lblMouseClicked
        this.dispose();
        new ForgotPasswordUI().setVisible(true);
    }//GEN-LAST:event_forgot_password_lblMouseClicked

    private void exit_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_lblMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exit_lblMouseClicked

    private void sidebarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMousePressed
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_sidebarMousePressed

    private void sidebarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_sidebarMouseDragged

    private void sidebarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidebarMouseReleased
        setOpacity((float)1.0);
    }//GEN-LAST:event_sidebarMouseReleased

    private void login_btn_lblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_btn_lblKeyReleased
        this.attempt_login();
    }//GEN-LAST:event_login_btn_lblKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel error_lbl;
    private javax.swing.JLabel exit_lbl;
    private javax.swing.JPanel exit_pnl;
    private javax.swing.JLabel forgot_password_lbl;
    private javax.swing.JLabel inv_mgmt_login_lbl;
    private javax.swing.JLabel login_btn_lbl;
    private javax.swing.JPanel login_btn_pnl;
    private javax.swing.JPanel login_pnl;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel user_icon_lbl;
    private javax.swing.JLabel user_login_heading_lbl;
    private javax.swing.JTextField username_input;
    private javax.swing.JLabel username_lbl;
    // End of variables declaration//GEN-END:variables

    private void attempt_login() {
        PreparedStatement ps;
        ResultSet rs;
        String username = username_input.getText();
        String password = String.valueOf(password_input.getPassword());
        
        String query = "Select * FROM `inv_users` WHERE `uname` = ? AND `upass` = ?";
        
        try {
            
            ps = DbConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, username);
            ps.setString(2, password);
            
            rs = ps.executeQuery();
            
            if(rs.next()) {
                error_lbl.setText("");
                this.dispose();
                new HomeUI().setVisible(true);
            } else {
                error_lbl.setText("Incorrect Login Credentials!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LoginUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
